version: "3.3"
services:
    api_db:
        container_name: api_db
        image: mysql:8.0
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - db_api_volume:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD:
            MYSQL_DATABASE: api
            MYSQL_USER: root
            MYSQL_PASSWORD: 1234
        networks:
            - app_network
        ports:
            - "3301:3306"

    api2_db:
        container_name: api2_db    
        image: mysql:8.0
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - db_api2_volume:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD:
            MYSQL_DATABASE: api2
            MYSQL_USER: root
            MYSQL_PASSWORD: 1234
        networks:
            - app_network
        ports:
            - "3302:3306"

    api_app:
        container_name: api_app
        build: .
        restart: always
        depends_on:
            - api_db
            - api2_db
        networks:
            - app_network
        ports:
            - "8090:80"

networks:
    app_network:

volumes:
    db_api_volume:
    db_api2_volume:
